<?php

namespace yozh\userworkactivity;

use yozh\base\Bootstrap as BaseBootstrap;

class Bootstrap extends BaseBootstrap
{
	public function bootstrap( $app )
	{
		parent::bootstrap( $app ); // TODO: Change the autogenerated stub
	}
	
}